=== BenzeneBots/robotic-scout-magic/form-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$comment": "WSM Form Format",
    "title": "Form",
    "properties": {
        "id": {
            "type": "string",
            "description": "Identifier, should be the filename without `.json`"
        },
        "name": {
            "type": "string",
            "description": "Display Name"
        },
        "description": {
            "type": "string",
            "description": "Short description displayed on the form page"
        },
        "items": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": ["text", "number"]
                    },
                    "label": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "required": [ "id", "name", "items"]
}

=== BenzeneBots/robotic-scout-magic/forms/example.json
{
    "$schema": "../form-schema.json",
    "id": "example",
    "name": "Example Form",
    "description": "Starter Example Form",
    "items": [
        {
            "type": "text",
            "label": "A thing"
        },
        {
            "type": "text",
            "label": "Another thing"
        }
    ]
}
